### ISSUE TITLE
Where is the entrance? After installation

### ISSUE THREAD

**Issue by damonchenjianglin** [GuidoPreite/DRB#10]

**Comment by GuidoPreite** [comment]
If you installed the Managed Solution version, you can find the application by going to the Apps selection.
Or you click in the top left corner where you see the current app name, or you go to this url (change it based on your instance url):

https://ABC.crmNUMBER.dynamics.com/main.aspx?forceUCI=1&pagetype=apps

Let me know if this solve your issue.
