### ISSUE TITLE
[Question] Integration with Dataverse Browser?

### ISSUE THREAD

**Issue by NicolasPrats** [GuidoPreite/DRB#18]
Hello,

I am the developer of a [Browser which eases the debugging of plugins](https://github.com/NicolasPrats/DvBrowser). I would like to add the ability to easily create Web Api requests into this browser. And the best tool for this purpose is your Dataverse REST Builder. So I'm considering to integrate it in the browser.

I have a few questions for you:

1) Are you okay with this integration? While the license permits me to do so, I want to ensure that you are comfortable with it as well.
2) My plan is to include the HTML/CSS/JS files directly in the browser. I noticed that the DRB detects its context (webresource, xrmtoolbox, ...). I believe I don't need any new context to support because I can make DRB believe that it is operating within a webresource. I need to test this approach, but I am fairly confident. Can you foresee any issues with this scenario?
3) I'm unsure about how to automatically obtain the latest version of your packages. I see that you provide a NuGet package for XrmToolbox. I could extract the web files from this package, but is there a more straightforward way to acquire only the latest version of the web files?

Thank you

**Comment by GuidoPreite** [comment]
Hi @NicolasPrats,
I know your tool, very interesting project. Regarding your questions.
1. You can integrate DRB inside it, no problems about that.
2. If you can piggyback an existing context (probably the default one as the managed solution) ok, if you need a specific context let me know and I can add it to a future release.
3. Latest version of the files are always the one inside the repository (that are also used for the demo with the github.io link), if I remember correctly Dataverse DevTools (https://github.com/Power-Maverick/DataverseDevTools-VSCode) loads the files directly from the repository (but I don't recall the exact way, the source code should contain it). 

Add me on LinkedIn and we can continue the discussion there, I close this issue.
