### ISSUE TITLE
[Enhancement] Support for Power Automate Dataverse Connector Parameters

### ISSUE THREAD

**Issue by LinnZawWin** [GuidoPreite/DRB#2]
For developers, it might be easy to grab the parameters for **Get a row by ID** and **List rows** actions from the URL from the generated code in Xrm.WebApi/jQuery/XMLHttpRequest/Portals tabs.

But it would be great to have a separate tab for the citizen developers with the values for the parameters in separate textboxes (just like the functionality in FetchXML Builder as per the following screenshot).
- Select columns
- Filter rows
- Sort By
- Expand Query
- Row count

That will be helpful for those organisations where the XrmToolBox is blocked by the IT policy.
![image](https://user-images.githubusercontent.com/14156926/142422582-8d4874f6-2984-47a8-9008-a044b192a40e.png)

**Comment by GuidoPreite** [comment]
Implemented in version 1.0.0.8
