### ISSUE TITLE
Error when importing the managed solution into my OnPremise Dynamics 365 9.1 environment

### ISSUE THREAD

**Issue by bahramzy** [GuidoPreite/DRB#22]
Hi

I am trying to import the managed solution into my on-premise dynamics 365 environment but I get the following error:
The error says: "The import file is too large to upload". When I select Download Log File I get an error saying the record doesn't exist.

Can you help please.

![image](https://github.com/GuidoPreite/DRB/assets/6544841/dbaf8925-1f12-45e1-b874-1d4bab1a2e93)

**Comment by GuidoPreite** [comment]
Hi @bahramzy, to be honest I don't have an OnPremise instance to try to import the solution, but the managed solution file is under 2 MB so the error should not appear. My best guess is that some service inside the CRM server is not running properly (like it can happen with the async service). Check if you can schedule a restart of the server and try again.
Also this is the first time I heard about this error. If you have updates please report them here.
Thanks

**Comment by bahramzy** [comment]
Thank you for the response. The error was not related to this tool. We had some issues in our Dynamics 365 installation, which we solved by running a repair from the Dynamics 365 server installation file.

**Comment by bahramzy** [comment]
I am closing the issue.
