### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by RajuMandapati09** [GuidoPreite/DRB#25]
[Write your comment/feedback/issue here]

---
- Deployment: Online
- DB Version: 9.2.24031.170
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68
- Tool Version: 1.0.0.43

**Comment by GuidoPreite** [comment]
what is not working exactly?
maybe you have this problem? https://github.com/GuidoPreite/DRB/issues/23
