### ISSUE TITLE
Dataverse Rest Builder requires MS Edge Web View2

### ISSUE THREAD

**Issue by RegardtduPreez** [GuidoPreite/DRB#26]
When opening the Dataverse REST Builder I get a message asking me to install Microsoft Edge WebView2 runtime.
I have installed and restarted multiple times, the Tool simply give me the same message over and over.
Please assist.
Dataverse REST Builder error](https://github.com/GuidoPreite/DRB/assets/165023627/9b8e0271-2bd1-4c52-a096-0a32148389c1)

**Comment by GuidoPreite** [comment]
@RegardtduPreez please check issue https://github.com/GuidoPreite/DRB/issues/23, there is explained how to mitigate the problem.

**Comment by RegardtduPreez** [comment]
Great, it works. thanks, keep well.
