### ISSUE TITLE
Dataverse REST builder not detecting edge Webview 2

### ISSUE THREAD

**Issue by rogerhillgsy** [GuidoPreite/DRB#28]
[Write your comment/feedback/issue here]

---
- Deployment: Online
- DB Version: 9.2.24044.212
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68
- Tool Version: 1.0.0.43

I'm getting a message that I need to install Microsoft WebView 2 when I try to start the REST Builder.

![image](https://github.com/GuidoPreite/DRB/assets/7746030/6ead89bb-ce6c-4d62-8efe-6e144c60bd4c)

When I try to install it, my computer is telling me that it is already installed. "$%$£$!!

Where do I go from here?

**Comment by GuidoPreite** [comment]
Hi @rogerhillgsy please check this issue https://github.com/GuidoPreite/DRB/issues/23
inside you will find a procedure to follow.
I close now this issue, feel free to reopen it in case you find difficulties on the proposed solution or write inside that issue.
Thanks
