### ISSUE TITLE
OData "EntityDefinition" end point, I can find a way to invoke as it doesn't appear to be an unbound action!

### ISSUE THREAD

**Issue by mrmwink** [GuidoPreite/DRB#29]
I absolutely love this tool, one of the biggest time savers in my day, keep up the good work.

I am hoping you can advise on how I can invoke the getEntitMetadata call that you make via WebApi, I think is uses the odata endpoint as follows.

[Organization URI]/api/data/v9.2/EntityDefinitions(LogicalName='account')?$select=DisplayName,IsKnowledgeManagementEnabled,EntitySetName

Is there a way to access this in the Dataverse Rest Builder with on the the defined options or do I need to find another call, move to the editor and then manually manipulate to run it?

Thanks

**Comment by GuidoPreite** [comment]
Hi @mrmwink, thanks for your feedback, I appreciate it.
As far as I know the metadata calls are not defined inside the metadata itself (neither inside the xml used for the internal function or by the EntityDefinitions endpoint), this is the reason you don't find that calls inside Dataverse REST Builder.

Adding them to Dataverse REST Builder will require a manual mapping and most of them are very complex (for example the calls to create new tables or attributes), I am not planning to add that endpoint.
Let me know if this answer your question.

**Comment by mrmwink** [comment]
Ok thanks, I was just writing a pcf control so making use of the getEntityMetada Utility call and as you know when using the PCF test harness you can't access the web API so instead I was building a mock service in the typescript so just wanted a quick may to generate a dummy response for the mock.

Thanks for the prompt response.

**Comment by BetimBeja** [comment]
@mrmwink I have mocked the component-framework give it a try?
https://github.com/Shko-Online/ComponentFramework-Mock
