### ISSUE TITLE
Batch requests

### ISSUE THREAD

**Issue by mrmwink** [GuidoPreite/DRB#31]
Hi,

Just a quick question, does the tool support creation of a batch request, I can't find it anywhere but wanted to check before I start building something to generate the request?

Thanks

Mike

**Comment by GuidoPreite** [comment]
Hi @mrmwink,
the tool does not generate batch requests, however the tool itself uses batch requests so you can check the code on how I implemented it, the relevant part is here
https://github.com/GuidoPreite/DRB/blob/0e7d46d9fd13da8d523c517241bc06960a4c4f63/js/drb.xrm.js#L147

let me know if this helps with your question.

**Comment by mrmwink** [comment]
@GuidoPreite That's amazing, thanks, I've not had much experience with the batch endpoint so this is perfect as it makes way more sense than the MSFT learning page :-)

**Comment by mrmwink** [comment]
Closing ticket
