### ISSUE TITLE
Batch Size Limitation in on premise versions

### ISSUE THREAD

**Issue by Pirata-Codex** [GuidoPreite/DRB#32]
Dynamics 365 applications usually use batch size of 100. In our organization the application didn't work and I've uploaded the screenshot of it. I realized that by slicing the request when creating the batch the problem will solve. I forked your project and fixed the problem but not sure whether it's the best solution.
Regardless of this issue, I wanted to thank you for developing this application. Great work! <3
[https://github.com/Pirata-Codex/DRB](url)
![error](https://github.com/user-attachments/assets/d49b5730-cfb7-4c21-b263-37ba5bcb725b)

**Comment by GuidoPreite** [comment]
Hi @Pirata-Codex thank you for issue explaining the problem you faced with batching.
As I understood this is happening with OnPremise so you are using the managed solution version. Probably the fork it is the best solution you have now.
Ideally in the future I should add a setting to define the batch size but to be honest this project is not on my priority list now.
I close this issue, feel free to contact me if you have questions.
