### ISSUE TITLE
Requested API version not understood

### ISSUE THREAD

**Issue by yusufaboobaker** [GuidoPreite/DRB#5]
Running PAAS version of CRM. Developer resources advise of API version 9.2. 
When retrieving columns, gives this error
![image](https://user-images.githubusercontent.com/8035351/146633913-83287780-8e74-46f7-a5e0-9450c8af3348.png)

**Comment by GuidoPreite** [comment]
@yusufaboobaker 
are you using the latest DRB version?
XrmToolBox version or Managed Solution version?
Exact version of your CRM instance?
Can you share the exact URL format you see in the top? (you can hide the information, like https://XYZ.crm.dynamics.com)
Thanks

**Comment by yusufaboobaker** [comment]
Hi, Thank you for your response. Please see screen shot for the info you require. Thanks again.

**Comment by GuidoPreite** [comment]
Thanks @yusufaboobaker , I saw your screenshot, I edited your comment and removed the image from it in order to hide info.
I understood the issue and I will try to publish a new release soon in order to mitigate this problem.

**Comment by GuidoPreite** [comment]
@yusufaboobaker I released a new version (1.0.0.18) that should solve your issue.
As you are using the XrmToolBox version, close XrmToolBox, when you open it should advise that an update is available, update Dataverse REST Builder (XrmToolBox will restart) and try to connect again to the instance where you were getting the error.
You should see the URL in the top not showing the trailing slash (before in your screenshot was _XYZ.crm4.dynamics.com/_ now it should be _XYZ.crm.dynamics.com_)
Let me know if the new version solve the issue. Thanks

**Comment by GuidoPreite** [comment]
Hi @yusufaboobaker, hopefully the new release solved the problem, if not please open a new issue or contact me directly. I close this issue, thanks again for reporting your problem.
