### ISSUE TITLE
Not compatible with 8.2

### ISSUE THREAD

**Issue by anagarajank** [GuidoPreite/DRB#6]

**Comment by GuidoPreite** [comment]
@anagarajank 
Dataverse REST Builder has been created with the support starting from 9.x mainly for these reasons:

- Unified Interface support started with Dynamics 365 v9.0
- I don't have access to a CRM 2016 instance (version 8.x) that I can use for development
- Some of the request types available (like Execute Custom API and probably also Manage File Data/Manage Image Data) are not available inside 8.x

There are other reasons as well (like browser compatibility).
I don't see a practical reason to work to support 8.x instances, keep in mind that you can use the [demo](https://guidopreite.github.io/DRB/) to create the required sample code for your request, you will need to change the endpoint version and the involved table/column names, but better than nothing.

I will keep open this issue for 3 days and after I will close it, feel free to comment if you want to add something.
